### ISSUE TITLE
-DWITH_RAPID=OFF results in ** ERROR: Could not find 'group_replication'

### ISSUE THREAD

**Issue by laurynas-biveinis** [Percona-Lab/ps-build#12]
group_replication is one of default MTR suites, but if GR is not built, it used to skip silently. But not anymore in new Jenkins it seems:
https://ps.cd.percona.com/job/percona-server-5.7-pipeline/1172/consoleFull:
```
+ ./mysql-test-run.pl --parallel=4 --result-file --unit-tests-report --debug-server --repeat=1 --mysqld=--loose-mecab-rc-file=/etc/mecabrc --force --max-test-fail=0 --suite-timeout=9999 --testcase-timeout=450
...
** ERROR: Could not find 'group_replication' or 'mtr' in ...
```

**Comment by delgod** [comment]
Hi @laurynas-biveinis,
I think group_replication suite should be installed by `make install` command...
what do you think?

**Comment by laurynas-biveinis** [comment]
I agree but see my comment on https://github.com/Percona-Lab/ps-build/issues/9 re. make install
