### ISSUE TITLE
Why Valgrind is disabled for MyRocks?

### ISSUE THREAD

**Issue by laurynas-biveinis** [Percona-Lab/ps-build#18]
https://ps.cd.percona.com/job/percona-server-5.7-valgrind-param/build?delay=0sec says

WITH_ROCKSDB | OFF |  
  | Compile RocksDB engine (infinity Loop on valgrind)

and there is no option to turn it ON

**Comment by delgod** [comment]
it is disabled due to infinity build, more than 4 days without any activities in output or any active load on the instance.
