### ISSUE TITLE
5.5 jobs do not need PerconaFT/Toku options

### ISSUE THREAD

**Issue by laurynas-biveinis** [Percona-Lab/ps-build#19]
These should be removed:

  | PERCONAFT_REPO |   |  
-- | -- | -- | --
  |   |  
  | URL to forked PerconaFT repository |  
  | PERCONAFT_BRANCH |   |  
  |   |  
  | Tag/Branch for PerconaFT repository |  
  | TOKUBACKUP_REPO |   |  
  |   |  
  | URL to forked Percona-TokuBackup repository |  
  | TOKUBACKUP_BRANCH |   |  
  |   |  
  | Tag/Branch for Percona-TokuBackup repository

**Comment by delgod** [comment]
please review https://github.com/Percona-Lab/ps-build/pull/25

**Comment by delgod** [comment]
fixed, thanks
