### ISSUE TITLE
Valgrind jobs must pass -DWITH_VALGRIND=ON to CMake

### ISSUE THREAD

**Issue by laurynas-biveinis** [Percona-Lab/ps-build#21]
And not -DUSE_VALGRIND=ON. Please check with @georgelorchpercona, maybe TokuDB requires the latter

**Comment by delgod** [comment]
both options passed to CMake, -DWITH_VALGRIND=ON passed always via ANALYZER_OPTS var.
-DUSE_VALGRIND=ON passed only if WITH_TOKUDB=ON.

@laurynas-biveinis -DUSE_VALGRIND=ON is needed for TokeDB, I have checked this information with @georgelorchpercona two times.

**Comment by laurynas-biveinis** [comment]
In the Valgrind build logs I have never seen -DWITH_VALGRIND=ON in actual CMake invocations

**Comment by delgod** [comment]
please review command like from https://ps.cd.percona.com/job/percona-server-5.7-valgrind-param/13/
downstream job log - https://ps.cd.percona.com/job/percona-server-5.7-pipeline/1361/consoleText

_+ /usr/bin/cmake -DCMAKE_BUILD_TYPE=Debug -DWITH_TOKUDB=ON -DWITH_ROCKSDB=OFF -DWITH_EMBEDDED_SERVER=ON -DWITH_RAPID=ON -DWITH_SSL=system -DWITH_MECAB=system -DBUILD_CONFIG=mysql_release -DFEATURE_SET=community -DENABLE_DTRACE=OFF -DENABLE_DOWNLOADS=ON -DWITH_PAM=ON -DWITH_SCALABILITY_METRICS=ON -DWITH_QUERY_RESPONSE_TIME=ON -DWITH_NUMA=ON -DWITH_INNODB_MEMCACHED=ON -DENABLE_DOWNLOADS=ON -DDOWNLOAD_ROOT=/tmp/results/source_downloads -DDOWNLOAD_BOOST=ON -DWITH_BOOST=/tmp/results/source_downloads -DWITH_KEYRING_VAULT=ON -DWITH_ZLIB=system -DCMAKE_INSTALL_PREFIX=/usr/local/Percona-Server-5.7.22-22-debug-valgrind-Linux.x86_64 -DMYSQL_DATADIR=/usr/local/Percona-Server-5.7.22-22-debug-valgrind-Linux.x86_64/data '-DCOMPILATION_COMMENT=Percona Server (GPL), Release 22, Revision 8664fd731b6-debug-valgrind' -DMYSQL_MAINTAINER_MODE=ON -DWITH_VALGRIND=ON -DDEBUG_EXTNAME=OFF -DBUILD_TESTING=OFF -DUSE_GTAGS=OFF -DUSE_CTAGS=OFF -DUSE_ETAGS=OFF -DUSE_CSCOPE=OFF -DTOKUDB_BACKUP_PLUGIN_VERSION=5.7.22-22 -DTOKU_DEBUG_PARANOID=ON -DUSE_VALGRIND=ON /tmp/ps_

**Comment by laurynas-biveinis** [comment]
@delgod, the 5.7 job indeed passes -DWITH_VALGRIND=ON, but I have not seen that option in 5.5 and 5.6 build logs (BTW 5.5 should not pass -DUSE_VALGRIND=ON because there is no TokuDB there)

**Comment by delgod** [comment]
could you please review this part of code https://github.com/Percona-Lab/ps-build/blob/5.7/local/build-binary#L126-L136
we pass USE_VALGRIND only if needed

**Comment by laurynas-biveinis** [comment]
I don't understand - the last part of my previous comment refers to 5.5 and this 5.7 code

**Comment by laurynas-biveinis** [comment]
OK, USE_VALGRIND looks good.
Valgrind TokuDB default should be the same as for the regular param build (enabled?)

**Comment by laurynas-biveinis** [comment]
re-checked, -DWITH_VALGRIND=ON is passed correctly, sorry for the false alarm
