### ISSUE TITLE
5.5 ASan broken

### ISSUE THREAD

**Issue by laurynas-biveinis** [Percona-Lab/ps-build#23]
Several testcases give
```
main.plugin_auth_qa_2                    w7 [ fail ]
        Test ended at 2018-06-27 06:44:12

CURRENT_TEST: main.plugin_auth_qa_2
==24022==AddressSanitizer Init done
==24023==AddressSanitizer Init done
__tls_get_addr: DTLS_Resize 0x7f7d8dc5c758 0
__tls_get_addr: 0x7f7d8cdcced0 {0x000000000001,0x000000000050} => 0x7f7d8dc5c778; tls_beg: 0x7f7d8dc5c728; sp: 0x7ffe0f88f7b0 num_live_dtls 1
__tls_get_addr: Can't guess glibc version
...
```

**Comment by delgod** [comment]
@laurynas-biveinis, could you please elaborate more on this?
should I pass some option for cmake or MTR or run test on another Ubuntu version?

**Comment by laurynas-biveinis** [comment]
At this point all I know is that old Jenkins does not give this

**Comment by delgod** [comment]
could you please help me to solve this issue?

according to comments in gcc code - `This may happen inside the DTOR of main thread, so just ignore it.`
see - https://github.com/gcc-mirror/gcc/blob/master/libsanitizer/sanitizer_common/sanitizer_tls_get_addr.cc#L119-L120

**Comment by laurynas-biveinis** [comment]
Cannot ignore it since it ruins test results. For some reason it's not happening in the old Jenkins.

ATM I have no idea for possible causes, my own troubleshooting would start with Google

**Comment by delgod** [comment]
@laurynas-biveinis I tried everything, I am lack of ideas, please help with the investigation

**Comment by laurynas-biveinis** [comment]
Discussing on the PR

**Comment by delgod** [comment]
ticket created - https://jira.percona.com/browse/PS-4562

**Comment by dbpercona** [comment]
can this be closed?   We can track in Jira issue if necessary

**Comment by laurynas-biveinis** [comment]
Yes
