### ISSUE TITLE
Allow core dumps

### ISSUE THREAD

**Issue by laurynas-biveinis** [Percona-Lab/ps-build#6]
Right now at e.g. https://jenkins.percona.com/job/mysql-5.7-param/1840/BUILD_TYPE=debug,Host=min-bionic-x64/consoleText:
`+ sudo sh -c 'ulimit -a && exec su jenkins'
...
coredump(blocks)     0`

**Comment by delgod** [comment]
fixed on Jenkins side, please review - https://github.com/Percona-Lab/jenkins-pipelines/pull/8

**Comment by delgod** [comment]
fixed on ps.cd.percona.com
