### ISSUE TITLE
MTR tests should run with a non-root user

### ISSUE THREAD

**Issue by laurynas-biveinis** [Percona-Lab/ps-build#8]
Right now, e.g. https://ps.cd.percona.com/job/percona-server-5.7-pipeline/1078/consoleText:
`[ERROR] Fatal error: Please read "Security" section of the manual to find out how to run mysqld as root!`

Please also add a whoami call for diagnostics

**Comment by delgod** [comment]
please review https://github.com/Percona-Lab/ps-build/pull/15

**Comment by delgod** [comment]
fixed in fact
```
main.drop-no_root                        w2 [ pass ]      4
```
MTR log - https://s3.us-east-2.amazonaws.com/ps-build-cache/jenkins-percona-server-5.6-pipeline-648/mtr.output.gz
