### ISSUE TITLE
audit_log MTR unable to find own include

### ISSUE THREAD

**Issue by laurynas-biveinis** [Percona-Lab/ps-build#9]
https://github.com/percona/percona-server/blob/5.7/plugin/audit_log/tests/mtr/audit_log_csv.test tries to include https://github.com/percona/percona-server/blob/5.7/plugin/audit_log/tests/mtr/audit_log_events.inc through `--source ../plugin/audit_log/tests/mtr/audit_log_events.inc`, but in the current Jenkins setup it's never found:

https://ps.cd.percona.com/job/percona-server-5.7-pipeline/1159/consoleText:
`mysqltest: At line 10: Could not open '/tmp/results/PS/plugin/audit_log/tests/mtr/audit_log_events.inc' for reading, errno: 2`

Probably something to do with pwd

**Comment by delgod** [comment]
@laurynas-biveinis, is `audit_log_events.inc` file installed by `make install` command?

**Comment by laurynas-biveinis** [comment]
@delgod, I don't know, it should be, if it's not, it's a packaging bug.

But I don't understand why you want to make install before running tests. Unless then the build procedure become 100% shared with release process - in which case it is very good, as we actually test what we ship. But if not, then it's just extra step, and lots of extra output in the logs - why?

**Comment by delgod** [comment]
I reworked jobs in [Continuous Delivery](https://en.wikipedia.org/wiki/Continuous_delivery) way.
Which usually looks like sequence of steps:
- commit
- build and achive binary
- run test1 on binary from build stage
- test2 on same binary
- test3 on same binary
- manual checking of same binary
- release same binary

one of major CD ideas is to test same binary on all stages (not some/random binary on each).
is Continuous Delivery workflow make sence?
our test and release proccess has no relation. but even without releasing same binary usualy it is right direction for movement.
but this proccess require fully working `make install` command and it is not "packaging bug", it is bug on cmake/make side.

**Comment by laurynas-biveinis** [comment]
OK
You are right, a cmake/make bug

**Comment by delgod** [comment]
@laurynas-biveinis, thank you!!
I have created [PS-4533](https://jira.percona.com/browse/PS-4533)

**Comment by dbpercona** [comment]
can this be closed?   We can track in Jira issue if necessary

**Comment by laurynas-biveinis** [comment]
Yes
